name: "Tests"

on:
  push:
    branches:
      - main
  pull_request_target:

permissions:
  contents: read
  pull-requests: read # allows SonarQube to decorate PRs with analysis results

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "22.x"
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Linting
        run: pnpm run lint

      - name: Tests
        run: pnpm run test

  scan:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: -Dsonar.projectKey=artus-engineering_react-gdpr-consent-banner_77b80343-758e-46a6-aaa4-a2f681f7d05d
            -Dsonar.sources=src -Dsonar.sourceEncoding=UTF-8
