name: Publish NPM Package

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Required for publishing to GitHub Packages
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@artus-engineering'

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Linting
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Publish to npm
        run: pnpm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
